# coding: utf-8

# flake8: noqa

"""
    SmartAPI API

    This is the API provided from [SmartAPI](http://smart-api.info) application.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: cwu@scripps.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi
from swagger_client.api.metadata_api import MetadataApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
