# coding: utf-8

# flake8: noqa
"""
    SmartAPI API

    This is the API provided from [SmartAPI](http://smart-api.info) application.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: cwu@scripps.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
